### ISSUE TITLE
[BUG]Can't get difference image

### ISSUE THREAD

**Issue by inviul** [romankh3/image-comparison#186] opened 2020-05-08 03:39 UTC
I am two versions of images, one is the baseline and another one is the actual where some changes are happening. This tool is not able to identify the changes, hence, not able to generate the difference image. Match state is coming in return.

Please help and thanks for this wonderful tool. Resolving the above issue will make it stronger.

**Comment by romankh3** [comment] 2020-05-08 04:33
Hello, @inviul.
Are you sure, that this is a bug?
As far as I understand, you speak about new behavior, right?

If it's really bug, please, provide test images for reproducing it.

if it's new behavior, let's discuss it in a proper issue topic.
Best regards,
Roman.

**Comment by MrMisterG** [comment] 2020-05-08 07:11
@inviul Maybe you have setPixelToleranceLevel too high?

**Comment by romankh3** [comment] 2020-06-03 18:42
There was no enough info about the bug, so I Close the issue due to timeout.

**Closed by romankh3** 2020-06-03 18:42 UTC
Labels: bug
