### ISSUE TITLE
[BUG] mergeRectangles hangs

### ISSUE THREAD

**Issue by HoverCatz** [romankh3/image-comparison#201] opened 2020-12-17 12:03 UTC
**Describe the bug**
The program hangs forever.

**To Reproduce**
1. Download attached zip and extract the 2 image files anywhere.
[files.zip](https://github.com/romankh3/image-comparison/files/5709166/files.zip)
2. Run this code:
> ImageComparison comparison = new ImageComparison("output_153.png", "output_154.png");
comparison.createMask(); // hangs forever

**Expected behavior**
Program should run and exit appropriately.

**Screenshots**
See attached zip above

**Java**
 - OS: Windows
 - openjdk version "1.8.0_252"

**Additional context**
I managed to trace this to the method `mergeRectangles`.
I don't know why it hangs, but I debugged it and the (minimum and maximum rectangles) are equal to the image size (width*height).
I **(thought I)** fixed it **(see my comment)** by skipping running `mergeRectangles` in a special scenario:
```
private List<Rectangle> populateRectangles() {
        long countOfDifferentPixels = populateTheMatrixOfTheDifferences();

        if (countOfDifferentPixels == 0) {
            return emptyList();
        }

        if (isAllowedPercentOfDifferentPixels(countOfDifferentPixels)) {
            return emptyList();
        }
        groupRegions();
        List<Rectangle> rectangles = new ArrayList<>();

        int minX = Integer.MAX_VALUE, minY = Integer.MAX_VALUE, maxX = Integer.MIN_VALUE, maxY = Integer.MIN_VALUE;

        while (counter <= regionCount) {
            Rectangle rectangle = createRectangle();
            if (!rectangle.equals(Rectangle.createDefault()) && rectangle.size() >= minimalRectangleSize) {
                rectangles.add(rectangle);
                Point min = rectangle.getMinPoint();
                Point max = rectangle.getMaxPoint();
                if (min.x < minX) minX = min.x;
                if (min.y < minY) minY = min.y;
                if (max.x > maxX) maxX = max.x;
                if (max.y > maxY) maxY = max.y;
            }
            counter++;
        }

        if (minX == 0 && minY == 0 &&
            maxX == actual.getWidth() - 1 &&
            maxY == actual.getHeight() - 1)
            return Collections.singletonList(new Rectangle(0, 0, maxX, maxY));

        return mergeRectangles(rectangles);
    }
```

**(I don't feel comfortable making a pull request).**

**Comment by HoverCatz** [comment] 2020-12-17 12:10
Not a permanent fix, not even close.
Just got this issue **again** somewhere else (2 other frames), it just hangs forever.
Damn thought I found a fix, my bad.
Still needs fixing.

**Comment by romankh3** [comment] 2020-12-17 13:26
Hello, @HoverCatz.
Thanks for your contributions.
I will see what can I do with it.

Best regards,
Roman.

**Comment by romankh3** [comment] 2021-03-01 09:52
Hi @HoverCatz.
You know, it's totally different images. `image-comparison` doesn't use for it.

**Comment by HoverCatz** [comment] 2021-03-01 10:49
Yes ofc they are different. `image-comparison` should recognize this and **not hang** itself...

**Comment by romankh3** [comment] 2021-03-01 12:29
I got it, thanks. We need to recognize it and stop comparing

**Comment by HoverCatz** [comment] 2021-03-01 12:30
Thank you! 🥇

**Comment by romankh3** [comment] 2021-03-13 19:22
@HoverCatz, bug fixed in 4.3.1 version.
Thanks, that you found a bug, investigate the place in which the problem is and create a bug report with provided images.

If you have any ideas of how to improve `image-comparison` feel free to write me about it.


Best regards,
Roman.

**Closed by romankh3** 2021-03-13 19:22 UTC
Labels: bug

**Comment by HoverCatz** [comment] 2021-04-16 22:14
I had a question! Is it possible to implement support to detect when 2 images are "almost" identical? For example randomized JPEG compression on the same image. The original images are the same, but the pixels aren't anymore thanks to compression. Hope you understand! 💯

**Comment by romankh3** [comment] 2021-04-17 05:11
Hi, @HoverCatz. 
I think this page can help you with you question: https://github.com/romankh3/image-comparison/wiki/Image-Comparison-with-Image-compression
