### ISSUE TITLE
Add usability to getMask[IMPROVEMENT]

### ISSUE THREAD

**Issue by mkytolai** [romankh3/image-comparison#99] opened 2019-05-31 12:05 UTC
Currently getMask only returns a single rectangle, it ignores nested rectangles.
I have an idea on how to expand the method, will probably submit it later today

**Comment by romankh3** [comment] 2019-05-31 12:27
Hello, @mkytolai.
Have you seen this issue? (https://github.com/romankh3/image-comparison/issues/98)
it's the first feedback from the real user about excluded areas.

**Comment by romankh3** [comment] 2019-05-31 12:31
it's duplicate of #95, is it?
If yes, please close this issue and comment in #95 .

**Comment by romankh3** [comment] 2019-06-04 07:13
@mkytolai, please follow #95.

**Closed by romankh3** 2019-06-04 07:13 UTC
Labels: enhancement
